name: Check Links

on:
  push:
    branches: [ main ]

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
        run:|
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install lxml

    - name: Check links
      run: blc https://docs.visionify.ai/
